# Generated by Django 3.0.5 on 2020-04-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200418_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='delete_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='location',
            name='delete_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='delete_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
